experiment:
  name: augmentation_night_gamma
  group: augmentation

augmentation:
  enabled: true
  name: night_gamma

  basic:
    color_jitter:
      enabled: false

  weather:
    enabled: true
    mode: target_condition
    target: night
    effect: gamma

    night:
      enabled: true

      gamma:
        prob: 0.3
        gamma_range: [1.4, 2.3]
