experiment:
  name: augmentation_weather_snow
  group: augmentation

augmentation:
  enabled: true
  name: weather_snow

  basic:
    color_jitter:
      enabled: false

  weather:
    enabled: true
    mode: target_condition
    target: snow
    effect: particle

    snow:
      enabled: true

      particle:
        prob: 0.3
        snowflake_count_range: [300, 1200]
        snowflake_radius_range: [1, 3]
        alpha_range: [0.15, 0.35]

      whiteness:
        prob: 0.3
        whiteness_alpha_range: [0.05, 0.18]
