experiment:
  name: augmentation_weather_fog
  group: augmentation

augmentation:
  enabled: true
  name: weather_fog

  basic:
    color_jitter:
      enabled: false

  weather:
    enabled: true
    mode: target_condition
    target: fog
    effect: haze

    fog:
      enabled: true

      haze:
        prob: 0.3
        intensity_range: [0.15, 0.4]
        atmospheric_light_range: [180, 255]

      contrast:
        prob: 0.3
        contrast_factor_range: [0.65, 0.95]
