experiment:
  name: augmentation_weather_night
  group: augmentation

augmentation:
  enabled: true
  name: weather_night

  basic:
    color_jitter:
      enabled: false

  weather:
    enabled: true
    mode: target_condition
    target: night
    effect: gamma

    night:
      enabled: true

      darkening:
        prob: 0.3
        brightness_factor_range: [0.4, 0.85]

      noise:
        prob: 0.3
        noise_std_range: [0.005, 0.03]

      gamma:
        prob: 0.3
        gamma_range: [1.4, 2.3]
