experiment:
  name: enhancement_gamma
  group: enhancement

enhancement:
  enabled: true
  name: gamma

  # gamma < 1.0: brighten
  # gamma > 1.0: darken
  gamma: 0.6

  # all, train, val, test 중 선택 가능
  apply_to: all

  # all 또는 ["night"] 등으로 condition 제한 가능
  apply_conditions: ["night"]