experiment:
  name: model_segformer
  group: model

model:
  name: "segformer"
  pretrained_name: "nvidia/segformer-b2-finetuned-cityscapes-1024-1024"
  num_classes: 19

  dropout: 0.1
  drop_path_rate: 0.1

  # full, freeze_s1, freeze_s12, freeze_s123, head_only
  freeze_mode: "full"

  train_norm_when_frozen: true
  align_corners: false
  ignore_mismatched_sizes: false

optimizer:
  name: "adamw"
  lr: 0.00006

  use_layerwise_lr: true
  encoder_lr_mult: 1.0
  head_lr_mult: 10.0

  weight_decay: 0.01

scheduler:
  name: "poly"
  power: 1.0
  eta_min: 0.0
  min_lr: 0.0
  warmup_epochs: 3

train:
  epochs: 100
  batch_size: 4
  num_workers: 4
  pin_memory: true
  amp: true
  grad_clip_norm: null
  log_interval: 20
  val_interval: 1